apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-iwov
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-iwov
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-iwov
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-iwov
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-iwov
    spec:
      containers:
      - image: quay.io/quay_xjiang/release-e2e-deploy-tenant/appstudio/dc-metro-map-iwov@sha256:45ad714b1d52fc05458d911522996aa192b554a24d062a045699bc8cd325b134
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
